---
services:
  eventstream:
    ports:
    - "${EVENTSTREAM_WEB_PORT}:4566"
  otel-collector:
    ports:
    - "${OTEL_COLLECTOR_COLLECTOR_PORT}:4318"
  grafana:
    environment:
    - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
    - "${GRAFANA_WEB_PORT}:3000"
  jaeger:
    ports:
    - "${JAEGER_WEB_PORT}:16686"
  prometheus:
    ports:
    - "${PROMETHEUS_WEB_PORT}:9090"
  user-db:
    environment:
    - POSTGRES_DB=${USER_DB_POSTGRES_DB}
    - POSTGRES_PASSWORD=${USER_DB_POSTGRES_PASSWORD}
    - POSTGRES_USER=${USER_DB_POSTGRES_USER}
    ports:
    - "${USER_DB_POSTGRES_PORT}:5432"
  user-service:
    environment:
    - CABLE_DATABASE_URL=${USER_DB_CABLE_DATABASE_URL}
    - CACHE_DATABASE_URL=${USER_DB_CACHE_DATABASE_URL}
    - DATABASE_URL=${USER_DB_DATABASE_URL}
    - QUEUE_DATABASE_URL=${USER_DB_QUEUE_DATABASE_URL}
    - SECRET_KEY_BASE="${USER_SECRET_KEY_BASE}"
    - RAILS_ENV=production
    - RAILS_MAX_THREADS=5
    - RAILS_MIN_THREADS=5
    ports:
    - "${USER_SERVICE_WEB_PORT}:3000"
    depends_on:
      user-db:
        condition: service_healthy
        restart: true
      user-db-cache:
        condition: service_healthy
        restart: true
      user-db-cable:
        condition: service_healthy
        restart: true
      user-db-queue:
        condition: service_healthy
        restart: true
  account-db:
    environment:
    - POSTGRES_DB=${ACCOUNT_DB_POSTGRES_DB}
    - POSTGRES_PASSWORD=${ACCOUNT_DB_POSTGRES_PASSWORD}
    - POSTGRES_USER=${ACCOUNT_DB_POSTGRES_USER}
    ports:
    - "${ACCOUNT_DB_POSTGRES_PORT}:5432"
  account-service:
    environment:
    - CABLE_DATABASE_URL=${ACCOUNT_DB_CABLE_DATABASE_URL}
    - CACHE_DATABASE_URL=${ACCOUNT_DB_CACHE_DATABASE_URL}
    - DATABASE_URL=${ACCOUNT_DB_DATABASE_URL}
    - QUEUE_DATABASE_URL=${ACCOUNT_DB_QUEUE_DATABASE_URL}
    - SECRET_KEY_BASE="${ACCOUNT_SECRET_KEY_BASE}"
    - RAILS_ENV=production
    - RAILS_MAX_THREADS=5
    - RAILS_MIN_THREADS=5
    ports:
    - "${ACCOUNT_SERVICE_WEB_PORT}:3000"
    depends_on:
      account-db:
        condition: service_healthy
        restart: true
      account-db-cache:
        condition: service_healthy
        restart: true
      account-db-cable:
        condition: service_healthy
        restart: true
      account-db-queue:
        condition: service_healthy
        restart: true
  authz-db:
    environment:
    - POSTGRES_DB=${AUTHZ_DB_POSTGRES_DB}
    - POSTGRES_PASSWORD=${AUTHZ_DB_POSTGRES_PASSWORD}
    - POSTGRES_USER=${AUTHZ_DB_POSTGRES_USER}
    ports:
    - "${AUTHZ_DB_POSTGRES_PORT}:5432"
  authorization-service:
    environment:
    - CABLE_DATABASE_URL=${AUTHZ_DB_CABLE_DATABASE_URL}
    - CACHE_DATABASE_URL=${AUTHZ_DB_CACHE_DATABASE_URL}
    - DATABASE_URL=${AUTHZ_DB_DATABASE_URL}
    - QUEUE_DATABASE_URL=${AUTHZ_DB_QUEUE_DATABASE_URL}
    - SECRET_KEY_BASE="${AUTHORIZATION_SECRET_KEY_BASE}"
    - RAILS_ENV=production
    - RAILS_MAX_THREADS=5
    - RAILS_MIN_THREADS=5
    ports:
    - "${AUTHORIZATION_SERVICE_WEB_PORT}:3000"
    depends_on:
      authz-db:
        condition: service_healthy
        restart: true
      authz-db-cache:
        condition: service_healthy
        restart: true
      authz-db-cable:
        condition: service_healthy
        restart: true
      authz-db-queue:
        condition: service_healthy
        restart: true
  organization-db:
    environment:
    - POSTGRES_DB=${ORGANIZATION_DB_POSTGRES_DB}
    - POSTGRES_PASSWORD=${ORGANIZATION_DB_POSTGRES_PASSWORD}
    - POSTGRES_USER=${ORGANIZATION_DB_POSTGRES_USER}
    ports:
    - "${ORGANIZATION_DB_POSTGRES_PORT}:5432"
  organization-service:
    environment:
    - CABLE_DATABASE_URL=${ORGANIZATION_DB_CABLE_DATABASE_URL}
    - CACHE_DATABASE_URL=${ORGANIZATION_DB_CACHE_DATABASE_URL}
    - DATABASE_URL=${ORGANIZATION_DB_DATABASE_URL}
    - SECRET_KEY_BASE="${ORGANIZATION_SECRET_KEY_BASE}"
    - QUEUE_DATABASE_URL=${ORGANIZATION_DB_QUEUE_DATABASE_URL}
    - RAILS_ENV=production
    - RAILS_MAX_THREADS=5
    - RAILS_MIN_THREADS=5
    ports:
    - "${ORGANIZATION_SERVICE_WEB_PORT}:3000"
    depends_on:
      organization-db:
        condition: service_healthy
        restart: true
      organization-db-cache:
        condition: service_healthy
        restart: true
      organization-db-cable:
        condition: service_healthy
        restart: true
      organization-db-queue:
        condition: service_healthy
        restart: true
  user-db-cache:
    environment:
    - POSTGRES_DB=${USER_DB_CACHE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${USER_DB_CACHE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${USER_DB_CACHE_POSTGRES_USER}
    ports:
    - "${USER_DB_CACHE_POSTGRES_PORT}:5432"
  user-db-cable:
    environment:
    - POSTGRES_DB=${USER_DB_CABLE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${USER_DB_CABLE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${USER_DB_CABLE_POSTGRES_USER}
    ports:
    - "${USER_DB_CABLE_POSTGRES_PORT}:5432"
  user-db-queue:
    environment:
    - POSTGRES_DB=${USER_DB_QUEUE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${USER_DB_QUEUE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${USER_DB_QUEUE_POSTGRES_USER}
    ports:
    - "${USER_DB_QUEUE_POSTGRES_PORT}:5432"
  account-db-cache:
    environment:
    - POSTGRES_DB=${ACCOUNT_DB_CACHE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${ACCOUNT_DB_CACHE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${ACCOUNT_DB_CACHE_POSTGRES_USER}
    ports:
    - "${ACCOUNT_DB_CACHE_POSTGRES_PORT}:5432"
  account-db-cable:
    environment:
    - POSTGRES_DB=${ACCOUNT_DB_CABLE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${ACCOUNT_DB_CABLE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${ACCOUNT_DB_CABLE_POSTGRES_USER}
    ports:
    - "${ACCOUNT_DB_CABLE_POSTGRES_PORT}:5432"
  account-db-queue:
    environment:
    - POSTGRES_DB=${ACCOUNT_DB_QUEUE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${ACCOUNT_DB_QUEUE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${ACCOUNT_DB_QUEUE_POSTGRES_USER}
    ports:
    - "${ACCOUNT_DB_QUEUE_POSTGRES_PORT}:5432"
  authz-db-cache:
    environment:
    - POSTGRES_DB=${AUTHZ_DB_CACHE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${AUTHZ_DB_CACHE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${AUTHZ_DB_CACHE_POSTGRES_USER}
    ports:
    - "${AUTHZ_DB_CACHE_POSTGRES_PORT}:5432"
  authz-db-cable:
    environment:
    - POSTGRES_DB=${AUTHZ_DB_CABLE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${AUTHZ_DB_CABLE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${AUTHZ_DB_CABLE_POSTGRES_USER}
    ports:
    - "${AUTHZ_DB_CABLE_POSTGRES_PORT}:5432"
  authz-db-queue:
    environment:
    - POSTGRES_DB=${AUTHZ_DB_QUEUE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${AUTHZ_DB_QUEUE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${AUTHZ_DB_QUEUE_POSTGRES_USER}
    ports:
    - "${AUTHZ_DB_QUEUE_POSTGRES_PORT}:5432"
  organization-db-cache:
    environment:
    - POSTGRES_DB=${ORGANIZATION_DB_CACHE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${ORGANIZATION_DB_CACHE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${ORGANIZATION_DB_CACHE_POSTGRES_USER}
    ports:
    - "${ORGANIZATION_DB_CACHE_POSTGRES_PORT}:5432"
  organization-db-cable:
    environment:
    - POSTGRES_DB=${ORGANIZATION_DB_CABLE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${ORGANIZATION_DB_CABLE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${ORGANIZATION_DB_CABLE_POSTGRES_USER}
    ports:
    - "${ORGANIZATION_DB_CABLE_POSTGRES_PORT}:5432"
  organization-db-queue:
    environment:
    - POSTGRES_DB=${ORGANIZATION_DB_QUEUE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${ORGANIZATION_DB_QUEUE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${ORGANIZATION_DB_QUEUE_POSTGRES_USER}
    ports:
    - "${ORGANIZATION_DB_QUEUE_POSTGRES_PORT}:5432"
  group-db:
    environment:
    - POSTGRES_DB=${GROUP_DB_POSTGRES_DB}
    - POSTGRES_PASSWORD=${GROUP_DB_POSTGRES_PASSWORD}
    - POSTGRES_USER=${GROUP_DB_POSTGRES_USER}
    ports:
    - "${GROUP_DB_POSTGRES_PORT}:5432"
  group-service:
    environment:
    - CABLE_DATABASE_URL=${GROUP_DB_CABLE_DATABASE_URL}
    - CACHE_DATABASE_URL=${GROUP_DB_CACHE_DATABASE_URL}
    - DATABASE_URL=${GROUP_DB_DATABASE_URL}
    - QUEUE_DATABASE_URL=${GROUP_DB_QUEUE_DATABASE_URL}
    - RAILS_ENV=production
    - RAILS_MAX_THREADS=5
    - RAILS_MIN_THREADS=5
    ports:
    - "${GROUP_SERVICE_WEB_PORT}:3000"
    depends_on:
      group-db:
        condition: service_healthy
        restart: true
      group-db-cache:
        condition: service_healthy
        restart: true
      group-db-cable:
        condition: service_healthy
        restart: true
      group-db-queue:
        condition: service_healthy
        restart: true
  group-db-cache:
    environment:
    - POSTGRES_DB=${GROUP_DB_CACHE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${GROUP_DB_CACHE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${GROUP_DB_CACHE_POSTGRES_USER}
    ports:
    - "${GROUP_DB_CACHE_POSTGRES_PORT}:5432"
  group-db-cable:
    environment:
    - POSTGRES_DB=${GROUP_DB_CABLE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${GROUP_DB_CABLE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${GROUP_DB_CABLE_POSTGRES_USER}
    ports:
    - "${GROUP_DB_CABLE_POSTGRES_PORT}:5432"
  group-db-queue:
    environment:
    - POSTGRES_DB=${GROUP_DB_QUEUE_POSTGRES_DB}
    - POSTGRES_PASSWORD=${GROUP_DB_QUEUE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${GROUP_DB_QUEUE_POSTGRES_USER}
    ports:
    - "${GROUP_DB_QUEUE_POSTGRES_PORT}:5432"

