---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch: {}
  memory_limiter:
    limit_mib: 500
    spike_limit_mib: 100
    check_interval: 5s
exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:9464
service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - batch
      - memory_limiter
      exporters:
      - otlp
    metrics:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - prometheus
