# frozen_string_literal: true

source "https://rubygems.org"

gem "authorization-context", path: "../authorization-context"
gem "authorized-resource", path: "../authorized-resource"
gemspec
gem "opentelemetry-sdk", "~> 1.8"
gem "rspec", "~> 3.13"
