# frozen_string_literal: true

source "https://rubygems.org"

gem "authorization-context", path: "../authorization-context"

gemspec

gem "activerecord", "~> 8.0.2"
gem "activeresource", "~> 6.1.4"
gem "json", "< 3"
gem "opentelemetry-sdk", "~> 1.8"
gem "rake", "~> 13.0"
gem "rspec", "~> 3.13"
