---
services:
  account-service: &account-service-template
    image: parent_account_id/account-service
    ports:
      - "${ACCOUNT_SERVICE_WEB_PORT}:3000"
    environment:
      - DATABASE_URL=${ACCOUNT_DB_DATABASE_URL}
      - RAILS_ENV=test
      - RAILS_MAX_THREADS=5
      - RAILS_MIN_THREADS=5
      - AUTHORIZATION_SERVICE_API_BASE_URL=http://authorization-service:80
      - ORGANIZATION_SERVICE_API_BASE_URL=http://organization-service:80
      - USER_SERVICE_API_BASE_URL=http://user-service:80
      - RAILS_SECRET_KEY_BASE=${ACCOUNT_RAILS_SECRET_KEY_BASE}
    build:
      context: "./account-service"
    depends_on:
      account-db:
        condition: service_healthy
        restart: true
  account-auth-service:
    <<: *account-service-template
    ports:
      - "${ACCOUNT_AUTH_SERVICE_WEB_PORT}:3000"

