---
services:
  authorization-service:
    image: parent_account_id/authorization-service
    ports:
    - "${AUTHORIZATION_SERVICE_WEB_PORT}:3000"
    environment:
    - DATABASE_URL=${AUTHZ_DB_DATABASE_URL}
    - RAILS_ENV=test
    - RAILS_MAX_THREADS=5
    - RAILS_MIN_THREADS=5
    build:
      context: "./authorization-service"
    depends_on:
      authz-db:
        condition: service_healthy
        restart: true
