---
services:
  grafana:
    image: grafana/grafana:13.1.0
    ports:
    - "${GRAFANA_WEB_PORT}:3000"
    environment:
    - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_SECURITY_DISABLE_INITIAL_ADMIN_PASSWORD_CHANGE=true
    volumes:
    - "./data/test/grafana:/var/lib/grafana"
    - "./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources"
    - "./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
    - "./grafana/dashboards:/var/lib/grafana/dashboards"
    user: "${HOST_UID}:${HOST_GID}"
