services:
  grants-create-service-worker: &grants-create-service-worker
    image: parent_account_id/authorization-service
    command: ["./bin/rails", "runner", "GrantsCreateQueueWorker.new.run"]
    environment:
      - GRANTS_SEED_QUEUE_URL=http://eventstream:4566/000000000000/grants_create
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - AWS_REGION=us-east-1
      - DATABASE_URL=${AUTHZ_DB_DATABASE_URL}
      - RAILS_ENV=test
      - RAILS_MAX_THREADS=5
      - RAILS_MIN_THREADS=5
      - RAILS_SECRET_KEY_BASE=${AUTHORIZATION_RAILS_SECRET_KEY_BASE}
    depends_on:
      - eventstream
      - authorization-service
  grants-create-service-worker-01:
    <<: *grants-create-service-worker
  grants-create-service-worker-02:
    <<: *grants-create-service-worker
  grants-create-service-worker-03:
    <<: *grants-create-service-worker
  grants-create-service-worker-04:
    <<: *grants-create-service-worker
  grants-create-service-worker-05:
    <<: *grants-create-service-worker
  grants-create-service-worker-06:
    <<: *grants-create-service-worker
  grants-create-service-worker-07:
    <<: *grants-create-service-worker
  grants-create-service-worker-08:
    <<: *grants-create-service-worker
  grants-create-service-worker-09:
    <<: *grants-create-service-worker
  grants-create-service-worker-10:
    <<: *grants-create-service-worker

