---
services:
  organization-service:
    image: parent_account_id/organization-service
    ports:
      - "${ORGANIZATION_SERVICE_WEB_PORT}:3000"
    environment:
      - DATABASE_URL=${ORGANIZATION_DB_DATABASE_URL}
      - RAILS_ENV=test
      - RAILS_MAX_THREADS=5
      - RAILS_MIN_THREADS=5
      - USER_SERVICE_API_BASE_URL=http://user-service:80
      - AUTHORIZATION_SERVICE_API_BASE_URL=http://authorization-service:80
      - SECRET_KEY_BASE=${ORGANIZATION_RAILS_SECRET_KEY_BASE}
    build:
      context: "./organization-service"
    depends_on:
      organization-db:
        condition: service_healthy
        restart: true
