---
services:
  user-service:
    image: parent_account_id/user-service
    ports:
      - "${USER_SERVICE_WEB_PORT}:3000"
    environment:
      - DATABASE_URL=${USER_DB_DATABASE_URL}
      - RAILS_ENV=test
      - RAILS_MAX_THREADS=5
      - RAILS_MIN_THREADS=5
      - SECRET_KEY_BASE=${USER_RAILS_SECRET_KEY_BASE}
    build:
      context: "./user-service"
    depends_on:
      user-db:
        condition: service_healthy
        restart: true
