---
services:
  user-management-service:
    image: parent_account_id/user-management-service
    build:
      context: "./user-management-service"
    environment:
      USER_SERVICE_API_BASE_URL: http://user-service:80
      ACCOUNT_SERVICE_API_BASE_URL: http://account-service:80
      ORGANIZATION_SERVICE_API_BASE_URL: http://organization-service:80
