---
services:
  user-management-service:
    image: parent_account_id/user-management-service
    ports:
      - "${USER_MANAGEMENT_WEB_PORT}:3000"
    build:
      context: "./user-management-service"
    environment:
      USER_SERVICE_API_BASE_URL: http://user-service:80
      ACCOUNT_SERVICE_API_BASE_URL: http://account-service:80
      ORGANIZATION_SERVICE_API_BASE_URL: http://organization-service:80
      SECRET_KEY_BASE: "${USER_MANAGEMENT_RAILS_SECRET_KEY_BASE}"
      AUTHORIZATION_SERVICE_API_BASE_URL: http://authorization-service:80
