# config/initializers/env_constants.rb

module Env
  AUTHORIZATION_SERVICE_API_BASE_URL = ENV.fetch("AUTHORIZATION_SERVICE_API_BASE_URL")
  ORGANIZATION_SERVICE_API_BASE_URL = ENV.fetch("ORGANIZATION_SERVICE_API_BASE_URL")
end

