require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { account_id: "28fb6349-0f1d-4642-81ca-8732c6115138", email: "foo@example.com" }
  }

  let(:invalid_attributes) {
    { account_id: nil, email: "foo@example.com" }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    { "pad-user-id" => "IAM_SYSTEM" }
  }

  describe "GET /index" do
    it "renders a successful response" do
      User.create! valid_attributes
      get users_url, params: { account_id: valid_attributes.fetch(:account_id) }, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user = User.create! valid_attributes
      get user_url(user), headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "read authorization" do
    let!(:user) { User.create!(valid_attributes) }

    it "checks account.users.read through authorization-service for individual users" do
      expect(User).to receive(:user_can?).with(
        user_id: "reader-user",
        permission: "account.users.read",
        account_ids: [valid_attributes.fetch(:account_id)]
      ).and_return(true)

      get user_url(user), headers: { "pad-user-id" => "reader-user" }, as: :json

      expect(response).to have_http_status(:ok), response.body
    end

    it "checks account.users.read once for collection account IDs" do
      expect(User).to receive(:user_can?).with(
        user_id: "reader-user",
        permission: "account.users.read",
        account_ids: [valid_attributes.fetch(:account_id)]
      ).and_return(true)

      post "/users/search",
           params: { account_id: [valid_attributes.fetch(:account_id)] },
           headers: { "pad-user-id" => "reader-user" },
           as: :json

      expect(response).to have_http_status(:ok)
    end

    it "returns loading when MSP reflected grants are still loading" do
      allow(User).to receive(:user_can?).and_return(false)
      expect(User).to receive(:msp_reflected_user_manage_users_check).with(
        user_id: "msp-admin",
        msp_account_id: "msp-account",
        account_ids: [valid_attributes.fetch(:account_id)]
      ).and_return(User::ReflectedAuthCheck.new(authorized?: false, loading?: true, status: "loading", loaded_count: 10, total_count: 100))

      post "/users/search",
           params: { account_id: [valid_attributes.fetch(:account_id)] },
           headers: { "pad-user-id" => "msp-admin", "pad-msp-account-id" => "msp-account" },
           as: :json

      expect(response).to have_http_status(:accepted)
      expect(JSON.parse(response.body)).to include("loading" => true, "loaded_count" => 10, "total_count" => 100)
    end

    it "returns forbidden when native and MSP reflected grants do not authorize the account" do
      allow(User).to receive(:user_can?).and_return(false)
      allow(User).to receive(:msp_reflected_user_manage_users_check).and_return(
        User::ReflectedAuthCheck.new(authorized?: false, loading?: false, status: "ready", loaded_count: 0, total_count: 0)
      )

      get user_url(user), headers: { "pad-user-id" => "reader-user" }, as: :json

      expect(response).to have_http_status(:forbidden)
    end

    it "checks account.users.read before returning user counts" do
      expect(User).to receive(:user_can?).with(
        user_id: "reader-user",
        permission: "account.users.read",
        account_ids: [valid_attributes.fetch(:account_id)]
      ).and_return(true)

      get users_counts_url,
          params: { account_id: [valid_attributes.fetch(:account_id)] },
          headers: { "pad-user-id" => "reader-user" },
          as: :json

      expect(response).to have_http_status(:ok)
      expect(JSON.parse(response.body)).to include(valid_attributes.fetch(:account_id) => 1)
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new User" do
        expect {
          post users_url,
               params: { user: valid_attributes }, headers: valid_headers, as: :json
        }.to change(User, :count).by(1)
      end

      it "renders a JSON response with the new user" do
        post users_url,
             params: { user: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new User" do
        expect {
          post users_url,
               params: { user: invalid_attributes }, as: :json
        }.to change(User, :count).by(0)
      end

      it "renders a JSON response with errors for the new user" do
        post users_url,
             params: { user: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested user" do
        user = User.create! valid_attributes
        patch user_url(user),
              params: { user: new_attributes }, headers: valid_headers, as: :json
        user.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the user" do
        user = User.create! valid_attributes
        patch user_url(user),
              params: { user: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the user" do
        user = User.create! valid_attributes
        patch user_url(user),
              params: { user: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user" do
      user = User.create! valid_attributes
      expect {
        delete user_url(user), headers: valid_headers, as: :json
      }.to change(User, :count).by(-1)
    end
  end
end
