require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { account_id: "28fb6349-0f1d-4642-81ca-8732c6115138", email: "foo@example.com" }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    { "pad-user-id" => "IAM_SYSTEM" }
  }

  describe "GET /index" do
    it "renders a successful response" do
      User.create! valid_attributes
      get "/users", params: { account_id: valid_attributes.fetch(:account_id) }, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user = User.create! valid_attributes
      get user_url(user), headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "read authorization" do
    let!(:user) { User.create!(valid_attributes) }

    it "checks account.users.read through authorization-service for individual users" do
      expect(User).to receive(:user_can?).with(
        user_id: "reader-user",
        permission: "account.users.read",
        account_ids: [valid_attributes.fetch(:account_id)]
      ).and_return(true)

      get user_url(user), headers: { "pad-user-id" => "reader-user" }, as: :json

      expect(response).to have_http_status(:ok), response.body
    end

    it "checks account.users.read once for collection account IDs" do
      expect(User).to receive(:user_can?).with(
        user_id: "reader-user",
        permission: "account.users.read",
        account_ids: [valid_attributes.fetch(:account_id)]
      ).and_return(true)

      post "/users/search",
           params: { account_id: [valid_attributes.fetch(:account_id)] },
           headers: { "pad-user-id" => "reader-user" },
           as: :json

      expect(response).to have_http_status(:ok)
    end

    it "ignores stale MSP headers and checks account.users.read" do
      expect(User).to receive(:user_can?).with(
        user_id: "msp-admin",
        permission: "account.users.read",
        account_ids: [valid_attributes.fetch(:account_id)]
      ).and_return(true)

      post "/users/search",
           params: { account_id: [valid_attributes.fetch(:account_id)] },
           headers: { "pad-user-id" => "msp-admin", "pad-msp-account-id" => "msp-account" },
           as: :json

      expect(response).to have_http_status(:ok)
    end

    it "returns forbidden when native grants do not authorize the account" do
      allow(User).to receive(:user_can?).and_return(false)

      get user_url(user), headers: { "pad-user-id" => "reader-user" }, as: :json

      expect(response).to have_http_status(:forbidden)
    end

    it "checks account.users.read before returning user counts" do
      expect(User).to receive(:user_can?).with(
        user_id: "reader-user",
        permission: "account.users.read",
        account_ids: [valid_attributes.fetch(:account_id)]
      ).and_return(true)

      get "/accounts/users/counts",
          params: { account_id: [valid_attributes.fetch(:account_id)] },
          headers: { "pad-user-id" => "reader-user" },
          as: :json

      expect(response).to have_http_status(:ok)
      expect(JSON.parse(response.body)).to include(valid_attributes.fetch(:account_id) => 1)
    end
  end

  describe "unsupported write routes" do
    it "does not expose create, update, or destroy routes" do
      post "/users", headers: valid_headers, as: :json
      expect(response).to have_http_status(:not_found)

      patch "/users/#{SecureRandom.uuid}", headers: valid_headers, as: :json
      expect(response).to have_http_status(:not_found)

      delete "/users/#{SecureRandom.uuid}", headers: valid_headers, as: :json
      expect(response).to have_http_status(:not_found)
    end
  end
end
